CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS greenhouse_db;
CREATE DATABASE IF NOT EXISTS sensor_db;
CREATE DATABASE IF NOT EXISTS ingestion_db;
CREATE DATABASE IF NOT EXISTS notification_db;
CREATE DATABASE IF NOT EXISTS analytics_db;