worker_processes  1;

events {
    worker_connections 1024;
}

# TCP Traffic
stream {
    server {
        listen 9000; 
        proxy_pass 127.0.0.1:9001; 
    }
}

# REST/SOAP Traffic
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  localhost;

        # Users Service
        location /api/users/ { 
            proxy_pass http://127.0.0.1:8081/; 
        }
        
        # Greenhouse Service
        location /api/greenhouse/ { 
            proxy_pass http://127.0.0.1:8082/; 
        }

        # Sensor Management Service (El inventario)
        location /api/management/ { 
            proxy_pass http://127.0.0.1:8083/; 
        }

        # Analytics Service
        location /api/analytics/ { 
            proxy_pass http://127.0.0.1:8084/; 
        }

        # Integration Service
        location /api/integration/ { 
            proxy_pass http://127.0.0.1:8085/; 
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
