syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.greenhouse.grpc.sensor";
option java_outer_classname = "SensorProto";

service SensorService {
  rpc GetSensorFormat (SensorRequest) returns (SensorFormatResponse);
  rpc GetSensorGreenhouseId (SensorRequest) returns (SensorGreenhouseResponse);


  rpc DeleteSensorsByGreenhouse (DeleteSensorsByGreenhouseRequest) returns (DeleteSensorsByGreenhouseResponse);
}

message SensorRequest { string serialNumber = 1; }
message SensorFormatResponse { string format = 1; }
message SensorGreenhouseResponse { int64 greenhouseId = 1; }

message DeleteSensorsByGreenhouseRequest { int64 greenhouseId = 1; }
message DeleteSensorsByGreenhouseResponse { int32 deletedCount = 1; }