
spring.application.name=greenhouse-service-test
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/greenhouse_db
spring.datasource.username=root
spring.datasource.password=mroMSQL1147-
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

grpc.server.port=9093